export const FACE_REF_BASE_PROMPT =
  'Create a professional character reference sheet of this exact character. Feature perfect character consistency and exact 1:1 likeness of the uploaded reference across all 3 panels. The image must be a vertical composite sheet divided into three equal horizontal rows. All panels prominently display the character on a pure white (#FFFFFF) background. The sheet must contain 3 distinct close-ups: Front View, 45-Degree Angle, Side Profile, with neutral face expression. The final image must be a true-to-life photography capturing real skin pores, fine lines, natural color variation, neutral expression, and authentic texture. Professional portrait photography with organic depth of field, preserving all natural human characteristics without digital smoothing or enhancement. 4K quality. No duplication of identical panels and no inconsistent features.'

// Seconde methode de fiche de reference (2026-09-24), proposee comme
// alternative explicite a FACE_REF_BASE_PROMPT -- jamais choisie
// automatiquement, voir le bouton "Essayer une autre methode" sur les ecrans
// qui appellent /api/generate/face-ref. Source : tmp/autres/PROMPTS.md #61,
// une grille 3x3 (9 portraits) plutot que 3 panneaux -- plus d angles
// couverts, verrouillage d echelle/eclairage explicite entre panneaux.
export const FACE_REF_ALT_PROMPT_9PANEL =
  'Create a highly realistic 3x3 portrait contact sheet of the same person, using the uploaded reference image as the primary guide for facial structure, hairstyle, clothing, lighting, and photographic style. Keep the exact same recognizable identity in all 9 panels: same face, same hairstyle, same outfit, same neutral warm-gray studio background, same soft diffused lighting, same camera distance and framing (head-and-shoulders, roughly 85mm portrait lens). No facial distortion, no identity drift between panels, no excessive retouching or plastic skin, natural skin texture with visible pores. Arrange exactly 9 panels in a 3 columns by 3 rows grid, equal panel sizes, no dividers or gaps. Row 1: front-facing portrait looking directly at camera; right-side profile; opposite three-quarter profile. Row 2: left three-quarter angle; right three-quarter angle; slightly lowered frontal angle. Row 3: low-angle portrait looking slightly upward; portrait looking downward; head gently tilted to one side. Photorealistic, sharp focus, high dynamic range, consistent scale and lighting across all nine frames. No cartoon, no CGI, no different person in different panels, no changing hairstyle or outfit between panels, no text, no watermark.'
